/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.source.view;

import com.source.dao.UsersDAO;

import com.source.utils.Auth;
import com.source.model.Users;
import com.source.utils.MsgBox;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author DELL
 */
public class A_DangNhapJDialog extends javax.swing.JDialog {
    UsersDAO dao = new UsersDAO();
    /**
     * Creates new form DangNhapJDialog
     */
    public A_DangNhapJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    void Progessbar(){
        this.setLocationRelativeTo(null);
        new Timer(20, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                int value = ProgressBar.getValue();
                if(value<100){
                    ProgressBar.setValue(value + 1);
                }else{
//                    ChaoJDialog.this.dispose();
                }
            }
        }).start();
    }
    public void setColor(JPanel panel){
        panel.setBackground(new java.awt.Color(240,240,240));
    }
    public void setColor1(JPanel panel){
        panel.setBackground(new java.awt.Color(255,255,255));
    }
    public void resetColor(JPanel panel){
        panel.setBackground(new java.awt.Color(204,0,0));
    }
    public void resetColor1(JPanel panel){
        panel.setBackground(new java.awt.Color(194,194,194));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        lblnen = new javax.swing.JLabel();
        pnl2 = new javax.swing.JPanel();
        txtusername = new javax.swing.JTextField();
        pnl3 = new javax.swing.JPanel();
        lblketthuc = new javax.swing.JLabel();
        pnl4 = new javax.swing.JPanel();
        lblSignin = new javax.swing.JLabel();
        lbllogo = new javax.swing.JLabel();
        Separator1 = new javax.swing.JSeparator();
        lbllogopassword = new javax.swing.JLabel();
        lbllogousernam = new javax.swing.JLabel();
        Separator2 = new javax.swing.JSeparator();
        lblthongbao = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        pnl5 = new javax.swing.JPanel();
        lblforgot = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnl1.setBackground(new java.awt.Color(0, 0, 0));

        lblnen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Images/nen1.jpg"))); // NOI18N

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                .addComponent(lblnen)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addComponent(lblnen)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnl2.setBackground(new java.awt.Color(255, 255, 255));

        txtusername.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtusername.setText("Username");
        txtusername.setBorder(null);

        pnl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl3MouseExited(evt);
            }
        });

        lblketthuc.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblketthuc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblketthuc.setText("Cancel");
        lblketthuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblketthucMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblketthucMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblketthucMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl3Layout = new javax.swing.GroupLayout(pnl3);
        pnl3.setLayout(pnl3Layout);
        pnl3Layout.setHorizontalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl3Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(lblketthuc)
                .addGap(63, 63, 63))
        );
        pnl3Layout.setVerticalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblketthuc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnl4.setBackground(new java.awt.Color(204, 0, 0));
        pnl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl4MouseExited(evt);
            }
        });

        lblSignin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblSignin.setForeground(new java.awt.Color(255, 255, 255));
        lblSignin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSignin.setText("Sign in");
        lblSignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSigninMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSigninMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSigninMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl4Layout = new javax.swing.GroupLayout(pnl4);
        pnl4.setLayout(pnl4Layout);
        pnl4Layout.setHorizontalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblSignin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl4Layout.setVerticalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSignin, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Images/nen002.jpg"))); // NOI18N

        lbllogopassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Images/password.png"))); // NOI18N

        lbllogousernam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Images/username.png"))); // NOI18N

        lblthongbao.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblthongbao.setForeground(new java.awt.Color(204, 0, 0));

        txtpassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtpassword.setText("1234567890");
        txtpassword.setBorder(null);
        txtpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpasswordMouseClicked(evt);
            }
        });

        pnl5.setBackground(new java.awt.Color(255, 255, 255));

        lblforgot.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblforgot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblforgot.setText("Forgot your password ?");
        lblforgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblforgotMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblforgotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblforgotMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl5Layout = new javax.swing.GroupLayout(pnl5);
        pnl5.setLayout(pnl5Layout);
        pnl5Layout.setHorizontalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblforgot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl5Layout.setVerticalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl5Layout.createSequentialGroup()
                .addComponent(lblforgot, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbllogo)
                            .addGroup(pnl2Layout.createSequentialGroup()
                                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbllogopassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbllogousernam, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblthongbao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Separator1)
                                    .addComponent(txtusername, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                    .addComponent(Separator2)
                                    .addComponent(txtpassword)))))
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnl4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnl5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbllogousernam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbllogopassword, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(txtpassword))
                .addComponent(Separator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblthongbao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(ProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblketthucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblketthucMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1){
            this.ketThuc();
        }
    }//GEN-LAST:event_lblketthucMouseClicked

    private void lblSigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSigninMouseClicked
        // TODO add your handling code here:
         check();
       
        try {
            if(evt.getClickCount() == 1){
                 String manv = txtusername.getText();
        String matkhau = new String(txtpassword.getPassword());
        Users userr = dao.selectById(manv);
        if (userr == null) {
            MsgBox.alert(this, "Sai tên đăng nhập");
            lblthongbao.setText("Sai tên đăng nhập !!!");

        } else if (!matkhau.equals(userr.getMatKhau())) {
            MsgBox.alert(this, "sai mật khẩu");;
            lblthongbao.setText("Sai mật khẩu !!!");

        } else {
            Auth.user = userr;
            Progessbar();
            this.dispose();
        
        };
            }
           
        } catch (ExceptionInInitializerError e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_lblSigninMouseClicked

    private void lblforgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblforgotMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1){
//            this.SignIn();
        }
    }//GEN-LAST:event_lblforgotMouseClicked

    private void txtpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1){
            txtpassword.setText("");
        }
    }//GEN-LAST:event_txtpasswordMouseClicked

    private void lblSigninMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSigninMouseExited
        // TODO add your handling code here:
        resetColor(pnl4);
    }//GEN-LAST:event_lblSigninMouseExited

    private void pnl4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl4MouseExited
        // TODO add your handling code here:
        resetColor(pnl4);
    }//GEN-LAST:event_pnl4MouseExited

    private void pnl4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl4MouseEntered
        // TODO add your handling code here:
        setColor(pnl4);
    }//GEN-LAST:event_pnl4MouseEntered

    private void lblSigninMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSigninMouseEntered
        // TODO add your handling code here:
        setColor(pnl4);
    }//GEN-LAST:event_lblSigninMouseEntered

    private void pnl4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl4MouseClicked
        // TODO add your handling code here:
        check();
       
        try {
            if(evt.getClickCount() == 1){
                 String manv = txtusername.getText();
        String matkhau = new String(txtpassword.getPassword());
        Users userr = dao.selectById(manv);
        if (userr == null) {
            MsgBox.alert(this, "Sai tên đăng nhập");
            lblthongbao.setText("Sai tên đăng nhập !!!");

        } else if (!matkhau.equals(userr.getMatKhau())) {
            MsgBox.alert(this, "sai mật khẩu");;
            lblthongbao.setText("Sai mật khẩu !!!");

        } else {
            Auth.user = userr;
            Progessbar();
            this.dispose();
        
        };
            }
           
        } catch (ExceptionInInitializerError e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_pnl4MouseClicked

    private void pnl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl3MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1){
            this.ketThuc();
        }
    }//GEN-LAST:event_pnl3MouseClicked

    private void pnl3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl3MouseExited
        // TODO add your handling code here:
        resetColor1(pnl3);
    }//GEN-LAST:event_pnl3MouseExited

    private void pnl3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl3MouseEntered
        // TODO add your handling code here:
        setColor(pnl3);
    }//GEN-LAST:event_pnl3MouseEntered

    private void lblketthucMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblketthucMouseExited
        // TODO add your handling code here:
        resetColor1(pnl3);
    }//GEN-LAST:event_lblketthucMouseExited

    private void lblketthucMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblketthucMouseEntered
        // TODO add your handling code here:
        setColor(pnl3);
    }//GEN-LAST:event_lblketthucMouseEntered

    private void lblforgotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblforgotMouseExited
        // TODO add your handling code here:
        setColor1(pnl5);
    }//GEN-LAST:event_lblforgotMouseExited

    private void lblforgotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblforgotMouseEntered
        // TODO add your handling code here:
        resetColor1(pnl5);
    }//GEN-LAST:event_lblforgotMouseEntered
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(A_DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(A_DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(A_DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(A_DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                A_DangNhapJDialog dialog = new A_DangNhapJDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JSeparator Separator1;
    private javax.swing.JSeparator Separator2;
    private javax.swing.JLabel lblSignin;
    private javax.swing.JLabel lblforgot;
    private javax.swing.JLabel lblketthuc;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lbllogopassword;
    private javax.swing.JLabel lbllogousernam;
    private javax.swing.JLabel lblnen;
    private javax.swing.JLabel lblthongbao;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnl4;
    private javax.swing.JPanel pnl5;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables

    public void init() {
//        setIconImage(XImage.getAppIcon());
        setTitle("HỆ THỐNG QUẢN LÝ ĐÀO TẠO");
        this.setLocationRelativeTo(null);
            txtusername.setText("");
    }
    public boolean check() {
        if (txtusername.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Username còn trống!");
//            txtusername.setBackground(Color.red);
            return false;
        } else {
//            txtusername.setBackground(Color.white);
        }
        if (txtpassword.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Password còn trống!");
//            txtpassword.setBackground(Color.red);
            return false;
        } else {
//            txtusername.setBackground(Color.white);
//            txtpassword.setBackground(Color.white);
        }
        return true;
    }
//    public void SignIn() {
//        check();
//        String Username = txtusername.getText();
//        String MatKhau = new String(txtpassword.getPassword());
//        try {
//            Users users = dao.selectById(Username);
//            if (users != null) {
//                String MatKhau2 = users.getMatKhau();
//                if (users.equals(MatKhau2)) {
//                    Auth.user = users;
//                    MsgBox.alert(this, "Đăng nhập thành công!");
//                    this.dispose();
//                } else {
//                    MsgBox.alert(this, "Sai mật khẩu!");
//                    lblthongbao.setText("Sai mật khẩu !!!");
//                }
//            } else {
//                MsgBox.alert(this, "Sai tên đăng nhập!");
//                lblthongbao.setText("Sai tên đăng nhập !!!");
//            }
//        } catch (Exception e) {
//            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
//        }
//    }

    public void ketThuc() {
        if (MsgBox.confirm(this, "Bạn muốn kết thúc ứng dụng?")) {
            System.exit(0);
        }
    }
  
}




