/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.source.view;

import com.source.utils.Auth;
import com.source.utils.MsgBox;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class BCaiDatJDialog extends javax.swing.JDialog {

    /**
     * Creates new form CaiDatJDialog
     */
    public BCaiDatJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public void setColor(JPanel panel){
        panel.setBackground(new java.awt.Color(150,150,150));
    }
     public void resetColor(JPanel panel){
        panel.setBackground(new java.awt.Color(255,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        pnldoimatkhau = new javax.swing.JPanel();
        lbldoimatkhau = new javax.swing.JLabel();
        pnlgioithieuphanmem = new javax.swing.JPanel();
        lblgioithieuphanmem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnl1.setBackground(new java.awt.Color(255, 255, 255));

        pnldoimatkhau.setBackground(new java.awt.Color(255, 255, 255));
        pnldoimatkhau.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnldoimatkhau.setLayout(new java.awt.BorderLayout());

        lbldoimatkhau.setBackground(new java.awt.Color(255, 255, 255));
        lbldoimatkhau.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbldoimatkhau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldoimatkhau.setText("ĐỔI MẬT KHẨU");
        lbldoimatkhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldoimatkhauMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbldoimatkhauMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbldoimatkhauMouseExited(evt);
            }
        });
        pnldoimatkhau.add(lbldoimatkhau, java.awt.BorderLayout.CENTER);

        pnlgioithieuphanmem.setBackground(new java.awt.Color(255, 255, 255));
        pnlgioithieuphanmem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlgioithieuphanmem.setLayout(new java.awt.BorderLayout());

        lblgioithieuphanmem.setBackground(new java.awt.Color(255, 255, 255));
        lblgioithieuphanmem.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblgioithieuphanmem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblgioithieuphanmem.setText("GIỚI THIỆU PHẦN MỀM");
        lblgioithieuphanmem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblgioithieuphanmemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblgioithieuphanmemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblgioithieuphanmemMouseExited(evt);
            }
        });
        pnlgioithieuphanmem.add(lblgioithieuphanmem, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlgioithieuphanmem, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(pnldoimatkhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnldoimatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlgioithieuphanmem, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(pnl1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbldoimatkhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldoimatkhauMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new A_DoiMatKhauJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_lbldoimatkhauMouseClicked

    private void lbldoimatkhauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldoimatkhauMouseEntered
        // TODO add your handling code here:
        setColor(pnldoimatkhau);
    }//GEN-LAST:event_lbldoimatkhauMouseEntered

    private void lbldoimatkhauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldoimatkhauMouseExited
        // TODO add your handling code here:
        resetColor(pnldoimatkhau);
    }//GEN-LAST:event_lbldoimatkhauMouseExited

    private void lblgioithieuphanmemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblgioithieuphanmemMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new A_GioiThieuJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_lblgioithieuphanmemMouseClicked

    private void lblgioithieuphanmemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblgioithieuphanmemMouseEntered
        // TODO add your handling code here:
        setColor(pnlgioithieuphanmem);
    }//GEN-LAST:event_lblgioithieuphanmemMouseEntered

    private void lblgioithieuphanmemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblgioithieuphanmemMouseExited
        // TODO add your handling code here:
        resetColor(pnlgioithieuphanmem);
    }//GEN-LAST:event_lblgioithieuphanmemMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BCaiDatJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BCaiDatJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BCaiDatJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BCaiDatJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BCaiDatJDialog dialog = new BCaiDatJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbldoimatkhau;
    private javax.swing.JLabel lblgioithieuphanmem;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnldoimatkhau;
    private javax.swing.JPanel pnlgioithieuphanmem;
    // End of variables declaration//GEN-END:variables
}
