/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.source.view;

import com.source.utils.MsgBox;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class C_QuanLyALLJDialog extends javax.swing.JDialog {

    /**
     * Creates new form QuanLyALLJDialog
     */
    public C_QuanLyALLJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
        ChuChay();
    }
    public void init(){
        this.setLocationRelativeTo(null);
    }
    javax.swing.Timer t ;
    public void ChuChay() {
        ActionListener a;
            a = new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                            String lbl = lblchay.getText();
                                lbl = lbl.substring(1, lbl.length())+lbl.charAt(0);
                                lblchay.setText(lbl);
                }
            };
       
          t = new javax.swing.Timer(200, a);
          t.start();
        
    }
    public void setColor(JPanel panel){
        panel.setBackground(new java.awt.Color(150,150,150));
    }
     public void resetColor(JPanel panel){
        panel.setBackground(new java.awt.Color(255,255,255));
    }
    public void resetColor51(JPanel panel){
        panel.setBackground(new java.awt.Color(0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        lbllogo = new javax.swing.JLabel();
        pnlnguoidung = new javax.swing.JPanel();
        lblnguoidung = new javax.swing.JLabel();
        lbllogonguoidung = new javax.swing.JLabel();
        pnlnhanvien = new javax.swing.JPanel();
        lblnhanvien = new javax.swing.JLabel();
        lbllogonhanvien = new javax.swing.JLabel();
        pnlkhachhang = new javax.swing.JPanel();
        lblkhachhang = new javax.swing.JLabel();
        lbllogokhachhang = new javax.swing.JLabel();
        pnlsanpham = new javax.swing.JPanel();
        lblsanpham = new javax.swing.JLabel();
        lbllogosanpham = new javax.swing.JLabel();
        pnlhoadon = new javax.swing.JPanel();
        lblhoadon = new javax.swing.JLabel();
        lbllogohoadon = new javax.swing.JLabel();
        pnlhopdong = new javax.swing.JPanel();
        lblhopdong = new javax.swing.JLabel();
        lbllogohopdong = new javax.swing.JLabel();
        pnlthongke = new javax.swing.JPanel();
        lblthongke = new javax.swing.JLabel();
        lbllogothongke = new javax.swing.JLabel();
        pnlbaocao = new javax.swing.JPanel();
        lblbaocao = new javax.swing.JLabel();
        lbllogobaocao = new javax.swing.JLabel();
        lblchuchay = new javax.swing.JPanel();
        pnl7 = new javax.swing.JPanel();
        lblhome = new javax.swing.JLabel();
        pnl4 = new javax.swing.JPanel();
        lbldangxuat = new javax.swing.JLabel();
        pnl5 = new javax.swing.JPanel();
        lblcaidat = new javax.swing.JLabel();
        pnl2 = new javax.swing.JPanel();
        pnl3 = new javax.swing.JPanel();
        lblchay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnl1.setBackground(new java.awt.Color(255, 255, 255));
        pnl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        lbllogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Icon/pannal.jpg"))); // NOI18N

        pnlnguoidung.setBackground(new java.awt.Color(255, 255, 255));
        pnlnguoidung.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlnguoidung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlnguoidungMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlnguoidungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlnguoidungMouseExited(evt);
            }
        });

        lblnguoidung.setBackground(new java.awt.Color(255, 255, 255));
        lblnguoidung.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblnguoidung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnguoidung.setText("NGƯỜI DÙNG");
        lblnguoidung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblnguoidungMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblnguoidungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblnguoidungMouseExited(evt);
            }
        });

        lbllogonguoidung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogonguoidung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Icon/UserBlack.png"))); // NOI18N
        lbllogonguoidung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllogonguoidungMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllogonguoidungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllogonguoidungMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlnguoidungLayout = new javax.swing.GroupLayout(pnlnguoidung);
        pnlnguoidung.setLayout(pnlnguoidungLayout);
        pnlnguoidungLayout.setHorizontalGroup(
            pnlnguoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlnguoidungLayout.createSequentialGroup()
                .addGroup(pnlnguoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblnguoidung, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(lbllogonguoidung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        pnlnguoidungLayout.setVerticalGroup(
            pnlnguoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnguoidungLayout.createSequentialGroup()
                .addComponent(lbllogonguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnguoidung)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlnhanvien.setBackground(new java.awt.Color(255, 255, 255));
        pnlnhanvien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlnhanvienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlnhanvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlnhanvienMouseExited(evt);
            }
        });

        lblnhanvien.setBackground(new java.awt.Color(255, 255, 255));
        lblnhanvien.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblnhanvien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnhanvien.setText("NHÂN VIÊN");
        lblnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblnhanvienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblnhanvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblnhanvienMouseExited(evt);
            }
        });

        lbllogonhanvien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogonhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Icon/NhanVienBlack.png"))); // NOI18N
        lbllogonhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllogonhanvienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllogonhanvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllogonhanvienMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlnhanvienLayout = new javax.swing.GroupLayout(pnlnhanvien);
        pnlnhanvien.setLayout(pnlnhanvienLayout);
        pnlnhanvienLayout.setHorizontalGroup(
            pnlnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblnhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
            .addComponent(lbllogonhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlnhanvienLayout.setVerticalGroup(
            pnlnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlnhanvienLayout.createSequentialGroup()
                .addComponent(lbllogonhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblnhanvien)
                .addContainerGap())
        );

        pnlkhachhang.setBackground(new java.awt.Color(255, 255, 255));
        pnlkhachhang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlkhachhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlkhachhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlkhachhangMouseExited(evt);
            }
        });

        lblkhachhang.setBackground(new java.awt.Color(255, 255, 255));
        lblkhachhang.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblkhachhang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblkhachhang.setText("KHÁCH HÀNG");
        lblkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblkhachhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblkhachhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblkhachhangMouseExited(evt);
            }
        });

        lbllogokhachhang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogokhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Icon/KhachHangBlack.png"))); // NOI18N
        lbllogokhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllogokhachhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllogokhachhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllogokhachhangMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlkhachhangLayout = new javax.swing.GroupLayout(pnlkhachhang);
        pnlkhachhang.setLayout(pnlkhachhangLayout);
        pnlkhachhangLayout.setHorizontalGroup(
            pnlkhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblkhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbllogokhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlkhachhangLayout.setVerticalGroup(
            pnlkhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlkhachhangLayout.createSequentialGroup()
                .addComponent(lbllogokhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblkhachhang)
                .addContainerGap())
        );

        pnlsanpham.setBackground(new java.awt.Color(255, 255, 255));
        pnlsanpham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlsanphamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlsanphamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlsanphamMouseExited(evt);
            }
        });

        lblsanpham.setBackground(new java.awt.Color(255, 255, 255));
        lblsanpham.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblsanpham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsanpham.setText("SẢN PHẨM");
        lblsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsanphamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblsanphamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblsanphamMouseExited(evt);
            }
        });

        lbllogosanpham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogosanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Icon/SanPhamBlack.png"))); // NOI18N
        lbllogosanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllogosanphamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllogosanphamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllogosanphamMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlsanphamLayout = new javax.swing.GroupLayout(pnlsanpham);
        pnlsanpham.setLayout(pnlsanphamLayout);
        pnlsanphamLayout.setHorizontalGroup(
            pnlsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblsanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbllogosanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlsanphamLayout.setVerticalGroup(
            pnlsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlsanphamLayout.createSequentialGroup()
                .addComponent(lbllogosanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblsanpham)
                .addContainerGap())
        );

        pnlhoadon.setBackground(new java.awt.Color(255, 255, 255));
        pnlhoadon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlhoadonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlhoadonMouseExited(evt);
            }
        });

        lblhoadon.setBackground(new java.awt.Color(255, 255, 255));
        lblhoadon.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblhoadon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhoadon.setText("HÓA ĐƠN");
        lblhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhoadonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblhoadonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblhoadonMouseExited(evt);
            }
        });

        lbllogohoadon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogohoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Icon/HoaDonBlack.png"))); // NOI18N
        lbllogohoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllogohoadonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllogohoadonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllogohoadonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlhoadonLayout = new javax.swing.GroupLayout(pnlhoadon);
        pnlhoadon.setLayout(pnlhoadonLayout);
        pnlhoadonLayout.setHorizontalGroup(
            pnlhoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblhoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbllogohoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlhoadonLayout.setVerticalGroup(
            pnlhoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlhoadonLayout.createSequentialGroup()
                .addComponent(lbllogohoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblhoadon)
                .addContainerGap())
        );

        pnlhopdong.setBackground(new java.awt.Color(255, 255, 255));
        pnlhopdong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlhopdong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlhopdongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlhopdongMouseExited(evt);
            }
        });

        lblhopdong.setBackground(new java.awt.Color(255, 255, 255));
        lblhopdong.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblhopdong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhopdong.setText("HỢP ĐỒNG");
        lblhopdong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblhopdongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblhopdongMouseExited(evt);
            }
        });

        lbllogohopdong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogohopdong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Icon/HopDongBlack.png"))); // NOI18N
        lbllogohopdong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllogohopdongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllogohopdongMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlhopdongLayout = new javax.swing.GroupLayout(pnlhopdong);
        pnlhopdong.setLayout(pnlhopdongLayout);
        pnlhopdongLayout.setHorizontalGroup(
            pnlhopdongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblhopdong, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
            .addComponent(lbllogohopdong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlhopdongLayout.setVerticalGroup(
            pnlhopdongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlhopdongLayout.createSequentialGroup()
                .addComponent(lbllogohopdong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblhopdong)
                .addContainerGap())
        );

        pnlthongke.setBackground(new java.awt.Color(255, 255, 255));
        pnlthongke.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlthongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlthongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlthongkeMouseExited(evt);
            }
        });

        lblthongke.setBackground(new java.awt.Color(255, 255, 255));
        lblthongke.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblthongke.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblthongke.setText("THỐNG KÊ");
        lblthongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblthongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblthongkeMouseExited(evt);
            }
        });

        lbllogothongke.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogothongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Icon/ThongKeBlack.png"))); // NOI18N
        lbllogothongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllogothongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllogothongkeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlthongkeLayout = new javax.swing.GroupLayout(pnlthongke);
        pnlthongke.setLayout(pnlthongkeLayout);
        pnlthongkeLayout.setHorizontalGroup(
            pnlthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblthongke, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
            .addComponent(lbllogothongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlthongkeLayout.setVerticalGroup(
            pnlthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlthongkeLayout.createSequentialGroup()
                .addComponent(lbllogothongke, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblthongke)
                .addContainerGap())
        );

        pnlbaocao.setBackground(new java.awt.Color(255, 255, 255));
        pnlbaocao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlbaocao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlbaocaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlbaocaoMouseExited(evt);
            }
        });

        lblbaocao.setBackground(new java.awt.Color(255, 255, 255));
        lblbaocao.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblbaocao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbaocao.setText("CHẤM CÔNG");
        lblbaocao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbaocaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblbaocaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblbaocaoMouseExited(evt);
            }
        });

        lbllogobaocao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogobaocao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Icon/BaoCaoBlack.png"))); // NOI18N
        lbllogobaocao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllogobaocaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllogobaocaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllogobaocaoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlbaocaoLayout = new javax.swing.GroupLayout(pnlbaocao);
        pnlbaocao.setLayout(pnlbaocaoLayout);
        pnlbaocaoLayout.setHorizontalGroup(
            pnlbaocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblbaocao, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
            .addComponent(lbllogobaocao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlbaocaoLayout.setVerticalGroup(
            pnlbaocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlbaocaoLayout.createSequentialGroup()
                .addComponent(lbllogobaocao, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblbaocao)
                .addContainerGap())
        );

        pnl7.setBackground(new java.awt.Color(0, 0, 0));
        pnl7.setLayout(new java.awt.BorderLayout());

        lblhome.setBackground(new java.awt.Color(0, 0, 0));
        lblhome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Icon/HomeBlack.png"))); // NOI18N
        lblhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblhomeMouseExited(evt);
            }
        });
        pnl7.add(lblhome, java.awt.BorderLayout.CENTER);

        pnl4.setBackground(new java.awt.Color(0, 0, 0));
        pnl4.setLayout(new java.awt.BorderLayout());

        lbldangxuat.setBackground(new java.awt.Color(255, 255, 255));
        lbldangxuat.setForeground(new java.awt.Color(255, 255, 255));
        lbldangxuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Icon/offWhite.png"))); // NOI18N
        lbldangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldangxuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbldangxuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbldangxuatMouseExited(evt);
            }
        });
        pnl4.add(lbldangxuat, java.awt.BorderLayout.CENTER);

        pnl5.setBackground(new java.awt.Color(0, 0, 0));
        pnl5.setLayout(new java.awt.BorderLayout());

        lblcaidat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcaidat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Icon/SettingsWhite.png"))); // NOI18N
        lblcaidat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcaidatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcaidatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcaidatMouseExited(evt);
            }
        });
        pnl5.add(lblcaidat, java.awt.BorderLayout.CENTER);

        pnl2.setBackground(new java.awt.Color(255, 255, 255));
        pnl2.setLayout(new java.awt.BorderLayout());

        pnl3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnl3Layout = new javax.swing.GroupLayout(pnl3);
        pnl3.setLayout(pnl3Layout);
        pnl3Layout.setHorizontalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );
        pnl3Layout.setVerticalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        pnl2.add(pnl3, java.awt.BorderLayout.CENTER);

        lblchay.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblchay.setForeground(new java.awt.Color(0, 153, 153));
        lblchay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblchay.setText("     CHÀO MỪNG ĐẾN VỚI SHOWROOM ETERNAL");
        pnl2.add(lblchay, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout lblchuchayLayout = new javax.swing.GroupLayout(lblchuchay);
        lblchuchay.setLayout(lblchuchayLayout);
        lblchuchayLayout.setHorizontalGroup(
            lblchuchayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
            .addGroup(lblchuchayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lblchuchayLayout.createSequentialGroup()
                    .addComponent(pnl7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 502, Short.MAX_VALUE)))
            .addGroup(lblchuchayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblchuchayLayout.createSequentialGroup()
                    .addGap(0, 500, Short.MAX_VALUE)
                    .addComponent(pnl4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(lblchuchayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblchuchayLayout.createSequentialGroup()
                    .addContainerGap(69, Short.MAX_VALUE)
                    .addComponent(pnl5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(431, Short.MAX_VALUE)))
            .addGroup(lblchuchayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))
        );
        lblchuchayLayout.setVerticalGroup(
            lblchuchayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
            .addGroup(lblchuchayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblchuchayLayout.createSequentialGroup()
                    .addGap(0, 22, Short.MAX_VALUE)
                    .addComponent(pnl7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(lblchuchayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblchuchayLayout.createSequentialGroup()
                    .addGap(0, 22, Short.MAX_VALUE)
                    .addComponent(pnl4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(lblchuchayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblchuchayLayout.createSequentialGroup()
                    .addGap(0, 22, Short.MAX_VALUE)
                    .addComponent(pnl5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(lblchuchayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblchuchayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlsanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlnguoidung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlnhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlhoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlkhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlhopdong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(pnlbaocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlthongke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblchuchay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbllogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlnguoidung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnlsanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlhopdong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addComponent(pnlhoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlbaocao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlthongke, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(lblchuchay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnl1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseEntered
        // TODO add your handling code here:
        setColor(pnl7);
    }//GEN-LAST:event_lblhomeMouseEntered

    private void lblhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseExited
        // TODO add your handling code here:
        resetColor51(pnl7);
    }//GEN-LAST:event_lblhomeMouseExited

    private void lbldangxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangxuatMouseClicked
        // TODO add your handling code here:
        new A_DangXuatJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_lbldangxuatMouseClicked

    private void lbldangxuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangxuatMouseEntered
        // TODO add your handling code here:
        setColor(pnl4);
    }//GEN-LAST:event_lbldangxuatMouseEntered

    private void lbldangxuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangxuatMouseExited
        // TODO add your handling code here:
        resetColor51(pnl4);
    }//GEN-LAST:event_lbldangxuatMouseExited

    private void lblcaidatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcaidatMouseClicked
        // TODO add your handling code here:
        new BCaiDatJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_lblcaidatMouseClicked

    private void lblcaidatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcaidatMouseEntered
        // TODO add your handling code here:
        setColor(pnl5);
    }//GEN-LAST:event_lblcaidatMouseEntered

    private void lblcaidatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcaidatMouseExited
        // TODO add your handling code here:
        resetColor51(pnl5);
    }//GEN-LAST:event_lblcaidatMouseExited

    private void lblhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new RUN_MAIN(111).setVisible(true);
    }//GEN-LAST:event_lblhomeMouseClicked

    private void lbllogonguoidungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogonguoidungMouseExited
        // TODO add your handling code here:
        resetColor(pnlnguoidung);
    }//GEN-LAST:event_lbllogonguoidungMouseExited

    private void lbllogonguoidungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogonguoidungMouseEntered
        // TODO add your handling code here:
        setColor(pnlnguoidung);
    }//GEN-LAST:event_lbllogonguoidungMouseEntered

    private void lbllogonguoidungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogonguoidungMouseClicked
        // TODO add your handling code here:
        new QLNguoiDungJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_lbllogonguoidungMouseClicked

    private void lblnguoidungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnguoidungMouseExited
        // TODO add your handling code here:
        resetColor(pnlnguoidung);
    }//GEN-LAST:event_lblnguoidungMouseExited

    private void lblnguoidungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnguoidungMouseEntered
        // TODO add your handling code here:
        setColor(pnlnguoidung);
    }//GEN-LAST:event_lblnguoidungMouseEntered

    private void lblnguoidungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnguoidungMouseClicked
        // TODO add your handling code here:
        new QLNguoiDungJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_lblnguoidungMouseClicked

    private void pnlnguoidungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlnguoidungMouseClicked
        // TODO add your handling code here:
        new QLNguoiDungJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_pnlnguoidungMouseClicked

    private void pnlnguoidungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlnguoidungMouseExited
        // TODO add your handling code here:
        resetColor(pnlnguoidung);
    }//GEN-LAST:event_pnlnguoidungMouseExited

    private void pnlnguoidungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlnguoidungMouseEntered
        // TODO add your handling code here:
        setColor(pnlnguoidung);
    }//GEN-LAST:event_pnlnguoidungMouseEntered

    private void lbllogonhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogonhanvienMouseClicked
        // TODO add your handling code here:
        new QLNhanVienJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_lbllogonhanvienMouseClicked

    private void lbllogonhanvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogonhanvienMouseExited
        // TODO add your handling code here:
        resetColor(pnlnhanvien);
    }//GEN-LAST:event_lbllogonhanvienMouseExited

    private void lbllogonhanvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogonhanvienMouseEntered
        // TODO add your handling code here:
        setColor(pnlnhanvien);
    }//GEN-LAST:event_lbllogonhanvienMouseEntered

    private void lblnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnhanvienMouseClicked
        // TODO add your handling code here:
        new QLNhanVienJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_lblnhanvienMouseClicked

    private void lblnhanvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnhanvienMouseExited
        // TODO add your handling code here:
        resetColor(pnlnhanvien);
    }//GEN-LAST:event_lblnhanvienMouseExited

    private void lblnhanvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnhanvienMouseEntered
        // TODO add your handling code here:
        setColor(pnlnhanvien);
    }//GEN-LAST:event_lblnhanvienMouseEntered

    private void pnlnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlnhanvienMouseClicked
        // TODO add your handling code here:
        new QLNhanVienJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_pnlnhanvienMouseClicked

    private void pnlnhanvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlnhanvienMouseExited
        // TODO add your handling code here:
        resetColor(pnlnhanvien);
    }//GEN-LAST:event_pnlnhanvienMouseExited

    private void pnlnhanvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlnhanvienMouseEntered
        // TODO add your handling code here:
        setColor(pnlnhanvien);
    }//GEN-LAST:event_pnlnhanvienMouseEntered

    private void lbllogokhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogokhachhangMouseClicked
        // TODO add your handling code here:
        new QLKhachHangJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_lbllogokhachhangMouseClicked

    private void lbllogokhachhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogokhachhangMouseExited
        // TODO add your handling code here:
        resetColor(pnlkhachhang);
    }//GEN-LAST:event_lbllogokhachhangMouseExited

    private void lbllogokhachhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogokhachhangMouseEntered
        // TODO add your handling code here:
        setColor(pnlkhachhang);
    }//GEN-LAST:event_lbllogokhachhangMouseEntered

    private void lblkhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblkhachhangMouseClicked
        // TODO add your handling code here:
        new QLKhachHangJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_lblkhachhangMouseClicked

    private void lblkhachhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblkhachhangMouseExited
        // TODO add your handling code here:
        resetColor(pnlkhachhang);
    }//GEN-LAST:event_lblkhachhangMouseExited

    private void lblkhachhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblkhachhangMouseEntered
        // TODO add your handling code here:
        setColor(pnlkhachhang);
    }//GEN-LAST:event_lblkhachhangMouseEntered

    private void pnlkhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlkhachhangMouseClicked
        // TODO add your handling code here:
        new QLKhachHangJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_pnlkhachhangMouseClicked

    private void pnlkhachhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlkhachhangMouseExited
        // TODO add your handling code here:
        resetColor(pnlkhachhang);
    }//GEN-LAST:event_pnlkhachhangMouseExited

    private void pnlkhachhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlkhachhangMouseEntered
        // TODO add your handling code here:
        setColor(pnlkhachhang);
    }//GEN-LAST:event_pnlkhachhangMouseEntered

    private void lbllogosanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogosanphamMouseClicked
        // TODO add your handling code here:
        new ThongTinSanPhamJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_lbllogosanphamMouseClicked

    private void lbllogosanphamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogosanphamMouseExited
        // TODO add your handling code here:
        resetColor(pnlsanpham);
    }//GEN-LAST:event_lbllogosanphamMouseExited

    private void lbllogosanphamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogosanphamMouseEntered
        // TODO add your handling code here:
        setColor(pnlsanpham);
    }//GEN-LAST:event_lbllogosanphamMouseEntered

    private void lblsanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsanphamMouseClicked
        // TODO add your handling code here:
        new ThongTinSanPhamJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_lblsanphamMouseClicked

    private void lblsanphamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsanphamMouseExited
        // TODO add your handling code here:
        resetColor(pnlsanpham);
    }//GEN-LAST:event_lblsanphamMouseExited

    private void lblsanphamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsanphamMouseEntered
        // TODO add your handling code here:
        setColor(pnlsanpham);
    }//GEN-LAST:event_lblsanphamMouseEntered

    private void pnlsanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlsanphamMouseClicked
        // TODO add your handling code here:
        new ThongTinSanPhamJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_pnlsanphamMouseClicked

    private void pnlsanphamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlsanphamMouseExited
        // TODO add your handling code here:
        resetColor(pnlsanpham);
    }//GEN-LAST:event_pnlsanphamMouseExited

    private void pnlsanphamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlsanphamMouseEntered
        // TODO add your handling code here:
        setColor(pnlsanpham);
    }//GEN-LAST:event_pnlsanphamMouseEntered

    private void lbllogohoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogohoadonMouseClicked
        // TODO add your handling code here:
        new DanhSachHoaDon(null, true).setVisible(true);
    }//GEN-LAST:event_lbllogohoadonMouseClicked

    private void lbllogohoadonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogohoadonMouseExited
        // TODO add your handling code here:
        resetColor(pnlhoadon);
    }//GEN-LAST:event_lbllogohoadonMouseExited

    private void lbllogohoadonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogohoadonMouseEntered
        // TODO add your handling code here:
        setColor(pnlhoadon);
    }//GEN-LAST:event_lbllogohoadonMouseEntered

    private void lblhoadonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhoadonMouseExited
        // TODO add your handling code here:
        resetColor(pnlhoadon);
    }//GEN-LAST:event_lblhoadonMouseExited

    private void lblhoadonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhoadonMouseEntered
        // TODO add your handling code here:
        setColor(pnlhoadon);
    }//GEN-LAST:event_lblhoadonMouseEntered

    private void pnlhoadonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhoadonMouseExited
        // TODO add your handling code here:
        resetColor(pnlhoadon);
    }//GEN-LAST:event_pnlhoadonMouseExited

    private void pnlhoadonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhoadonMouseEntered
        // TODO add your handling code here:
        setColor(pnlhoadon);
    }//GEN-LAST:event_pnlhoadonMouseEntered

    private void lbllogohopdongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogohopdongMouseEntered
        // TODO add your handling code here:
        setColor(pnlhopdong);
    }//GEN-LAST:event_lbllogohopdongMouseEntered

    private void lblhopdongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhopdongMouseExited
        // TODO add your handling code here:
        resetColor(pnlhopdong);
    }//GEN-LAST:event_lblhopdongMouseExited

    private void pnlhopdongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhopdongMouseExited
        // TODO add your handling code here:
        resetColor(pnlhopdong);
    }//GEN-LAST:event_pnlhopdongMouseExited

    private void pnlhopdongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhopdongMouseEntered
        // TODO add your handling code here:
        setColor(pnlhopdong);
    }//GEN-LAST:event_pnlhopdongMouseEntered

    private void lblhopdongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhopdongMouseEntered
        // TODO add your handling code here:
        setColor(pnlhopdong);
    }//GEN-LAST:event_lblhopdongMouseEntered

    private void lbllogohopdongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogohopdongMouseExited
        // TODO add your handling code here:
        resetColor(pnlhopdong);
    }//GEN-LAST:event_lbllogohopdongMouseExited

    private void lbllogobaocaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogobaocaoMouseExited
        // TODO add your handling code here:
        resetColor(pnlbaocao);
    }//GEN-LAST:event_lbllogobaocaoMouseExited

    private void lblbaocaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbaocaoMouseExited
        // TODO add your handling code here:
        resetColor(pnlbaocao);
    }//GEN-LAST:event_lblbaocaoMouseExited

    private void pnlbaocaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlbaocaoMouseExited
        // TODO add your handling code here:
        resetColor(pnlbaocao);
    }//GEN-LAST:event_pnlbaocaoMouseExited

    private void pnlbaocaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlbaocaoMouseEntered
        // TODO add your handling code here:
        setColor(pnlbaocao);
    }//GEN-LAST:event_pnlbaocaoMouseEntered

    private void lblbaocaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbaocaoMouseEntered
        // TODO add your handling code here:
        setColor(pnlbaocao);
    }//GEN-LAST:event_lblbaocaoMouseEntered

    private void lbllogobaocaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogobaocaoMouseEntered
        // TODO add your handling code here:
        setColor(pnlbaocao);
    }//GEN-LAST:event_lbllogobaocaoMouseEntered

    private void lbllogothongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogothongkeMouseExited
        // TODO add your handling code here:
        resetColor(pnlthongke);
    }//GEN-LAST:event_lbllogothongkeMouseExited

    private void lblthongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthongkeMouseExited
        // TODO add your handling code here:
        resetColor(pnlthongke);
    }//GEN-LAST:event_lblthongkeMouseExited

    private void pnlthongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlthongkeMouseExited
        // TODO add your handling code here:
        resetColor(pnlthongke);
    }//GEN-LAST:event_pnlthongkeMouseExited

    private void lbllogothongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogothongkeMouseEntered
        // TODO add your handling code here:
        setColor(pnlthongke);
    }//GEN-LAST:event_lbllogothongkeMouseEntered

    private void lblthongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthongkeMouseEntered
        // TODO add your handling code here:
        setColor(pnlthongke);
    }//GEN-LAST:event_lblthongkeMouseEntered

    private void pnlthongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlthongkeMouseEntered
        // TODO add your handling code here:
        setColor(pnlthongke);
    }//GEN-LAST:event_pnlthongkeMouseEntered

    private void lblhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhoadonMouseClicked
        // TODO add your handling code here:
        new DanhSachHoaDon(null, true).setVisible(true);
    }//GEN-LAST:event_lblhoadonMouseClicked

    private void lbllogobaocaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogobaocaoMouseClicked
        // TODO add your handling code here:
        ChamCOng chamCOng = new ChamCOng();
        chamCOng.setVisible(true);
    }//GEN-LAST:event_lbllogobaocaoMouseClicked

    private void lblbaocaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbaocaoMouseClicked
        // TODO add your handling code here:
             ChamCOng chamCOng = new ChamCOng();
        chamCOng.setVisible(true);
    }//GEN-LAST:event_lblbaocaoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_QuanLyALLJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_QuanLyALLJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_QuanLyALLJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_QuanLyALLJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                C_QuanLyALLJDialog dialog = new C_QuanLyALLJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblbaocao;
    private javax.swing.JLabel lblcaidat;
    private javax.swing.JLabel lblchay;
    private javax.swing.JPanel lblchuchay;
    private javax.swing.JLabel lbldangxuat;
    private javax.swing.JLabel lblhoadon;
    private javax.swing.JLabel lblhome;
    private javax.swing.JLabel lblhopdong;
    private javax.swing.JLabel lblkhachhang;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lbllogobaocao;
    private javax.swing.JLabel lbllogohoadon;
    private javax.swing.JLabel lbllogohopdong;
    private javax.swing.JLabel lbllogokhachhang;
    private javax.swing.JLabel lbllogonguoidung;
    private javax.swing.JLabel lbllogonhanvien;
    private javax.swing.JLabel lbllogosanpham;
    private javax.swing.JLabel lbllogothongke;
    private javax.swing.JLabel lblnguoidung;
    private javax.swing.JLabel lblnhanvien;
    private javax.swing.JLabel lblsanpham;
    private javax.swing.JLabel lblthongke;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnl4;
    private javax.swing.JPanel pnl5;
    private javax.swing.JPanel pnl7;
    private javax.swing.JPanel pnlbaocao;
    private javax.swing.JPanel pnlhoadon;
    private javax.swing.JPanel pnlhopdong;
    private javax.swing.JPanel pnlkhachhang;
    private javax.swing.JPanel pnlnguoidung;
    private javax.swing.JPanel pnlnhanvien;
    private javax.swing.JPanel pnlsanpham;
    private javax.swing.JPanel pnlthongke;
    // End of variables declaration//GEN-END:variables
}
