/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.source.view;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;


import com.source.dao.GioHangDAO;
import com.source.dao.KhachHangDAO;
import com.source.dao.NhanVienDAO;
import com.source.dao.HoaDonDAO;
import com.source.dao.SanPhamDAO;

import com.source.model.GioHang;
import com.source.model.KhachHang;
import com.source.model.HoaDon;
import com.source.model.SanPham;

import com.source.utils.Auth;
import com.source.utils.MsgBox;
import com.source.utils.XDate;
import com.source.utils.XImages;
import com.source.utils.XJDBC;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.Hashtable;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class GioHangJFrame extends javax.swing.JFrame {

 
    HoaDonDAO hddao = new HoaDonDAO();
    KhachHangDAO khdao = new KhachHangDAO();
    NhanVienDAO nvdao = new NhanVienDAO();
    public static String MaSP;
    public static double SoLuong;
  //  public static int MaHoaDon;
    GioHangDAO ghdao = new GioHangDAO();
    
    SanPhamDAO spdao= new SanPhamDAO();
    List<SanPham> sp = new ArrayList<SanPham>();
      GioHang gh = new GioHang();

    int row = 0;
    Double tongTien;

    /**
     * Creates new form GioHangJFrame
     */
    public GioHangJFrame() {
        initComponents();
        fillTable();
        this.setLocationRelativeTo(null);
        fillCbxKhachHang();
        init();
       
//    new QLSanPhamJDialog(this, true).setVisible(true);
    }
 
    void fillTable() {
        DefaultTableModel model1 = (DefaultTableModel) tblHoaDon.getModel();
        model1.setRowCount(0);
        DefaultTableModel model = (DefaultTableModel) tblGiohang.getModel();
        model.setRowCount(0);
        try {
            String keyword = "";
            List<GioHang> list = ghdao.selectByKeyword(keyword);
//            List<SanPham> list = dao.selectAll();
            for (GioHang gh : list) {
                Object[] row = {
                    gh.getMaGH(),
                    gh.getMaSP(),
                    gh.getSoLuong(),
                    gh.getDonGia()

                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    void  fillCbxKhachHang(){
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbxkhachhang.getModel();
        model.removeAllElements();
        
            List<KhachHang> list = khdao.selectAll();
          //  List<KhachHang> list = khdao.selectByKhachHang(KhachHang.getHoTen());
          // List<KhachHang> list = khdao.selectByKeyword(KhachHang.getHoTen());
            for (KhachHang khachHang : list) {
                model.addElement(khachHang);
              
                 cbxkhachhang.setToolTipText(khachHang.getMaKH());
                 cbxkhachhang.setSelectedItem(khdao.selectById(khachHang.getMaKH()));
                
        }
    }

    private void ThemHoaDonCT(String masp, String tensp, double soluong, double dongia, double thanhtien) {
        DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
        Object[] o = new Object[6];

        o[0] = model.getRowCount() + 1;
        o[1] = masp;
        o[2] = tensp;
        
        o[3] = soluong;
        o[4] = GioHangDAO.DinhDangTien(dongia);
        o[5] = GioHangDAO.DinhDangTien(thanhtien) + " $";
        model.addRow(o);
    }

    private double TongTien() {
        double tongTien = 0;
        for (int i = 0; i < tblHoaDon.getRowCount(); i++) {
            tongTien += GioHangDAO.ChuyenTien(tblHoaDon.getValueAt(i, 5).toString());
        }

        return tongTien;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        btnXemTruoc = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        btnIn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTongTien = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTienNhan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbl_TienThua = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGiohang = new javax.swing.JTable();
        btnChonThemSP = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        rdoThanhToanXong = new javax.swing.JRadioButton();
        rdoTraGop = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaGH = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        btnDeleteSP = new javax.swing.JButton();
        btnLuuHoaDon = new javax.swing.JButton();
        cbxkhachhang = new javax.swing.JComboBox<>();
        btnDanhSachHoaDon = new javax.swing.JButton();
        DateChooser = new com.toedter.calendar.JDateChooser();
        lblHInh = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btnReset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnXemTruoc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnXemTruoc.setText("Generat Receipt");
        btnXemTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemTruocActionPerformed(evt);
            }
        });

        area.setColumns(20);
        area.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        area.setRows(5);
        area.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, area, org.jdesktop.beansbinding.ELProperty.create("đây là phần mình xem được trước cái hóa đơn để in ra á"), area, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
        bindingGroup.addBinding(binding);

        jScrollPane2.setViewportView(area);

        btnIn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnIn.setText("Print  Recceipt");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblTongTien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTongTien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTongTien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Tổng tiền:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Số tiền thực nhận:");

        txtTienNhan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtTienNhan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtTienNhan, org.jdesktop.beansbinding.ELProperty.create("đây là tiền thực nhận từ khách hàng ($)"), txtTienNhan, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
        bindingGroup.addBinding(binding);

        txtTienNhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienNhanKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Tiền thừa:");

        lbl_TienThua.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_TienThua.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_TienThua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lbl_TienThua, org.jdesktop.beansbinding.ELProperty.create("tiền thừa khách hàng là đây nha(âm là trả góp á)"), lbl_TienThua, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
        bindingGroup.addBinding(binding);

        lbl_TienThua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbl_TienThuaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtTienNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lbl_TienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_TienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtTienNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "GIỎ HÀNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(204, 0, 0))); // NOI18N

        tblGiohang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tblGiohang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MaSP", "Đơn giá", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGiohang.setRowHeight(30);
        tblGiohang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGiohangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGiohang);
        if (tblGiohang.getColumnModel().getColumnCount() > 0) {
            tblGiohang.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblGiohang.getColumnModel().getColumn(3).setPreferredWidth(0);
        }

        btnChonThemSP.setBackground(new java.awt.Color(204, 0, 0));
        btnChonThemSP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnChonThemSP.setText("Add Product");
        btnChonThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonThemSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnChonThemSP)
                .addContainerGap(191, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnChonThemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HÓA ĐƠN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 51, 51))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdoThanhToanXong.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoThanhToanXong);
        rdoThanhToanXong.setText("Đã thanh toán");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, rdoThanhToanXong, org.jdesktop.beansbinding.ELProperty.create("thanh toán rồi thì click vào đây"), rdoThanhToanXong, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
        bindingGroup.addBinding(binding);

        jPanel5.add(rdoThanhToanXong, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        rdoTraGop.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoTraGop);
        rdoTraGop.setText("Trả Góp");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, rdoTraGop, org.jdesktop.beansbinding.ELProperty.create("muốn trả góp thì click zô đây"), rdoTraGop, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
        bindingGroup.addBinding(binding);

        rdoTraGop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTraGopActionPerformed(evt);
            }
        });
        jPanel5.add(rdoTraGop, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tên khách hàng");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 21, 115, 29));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Trạng Thái");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 119, 91, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ngày Lập");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 70, 29));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtMaGH, org.jdesktop.beansbinding.ELProperty.create("Mã giỏ hàng( nhập mã giỏ hàng tiếp theo có trong danh sách hóa đơn)"), txtMaGH, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
        bindingGroup.addBinding(binding);

        jPanel5.add(txtMaGH, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 160, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Mã GH");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 98, -1));

        tblHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        tblHoaDon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Tên SP", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon.setRowHeight(30);
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblHoaDon);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 242, 670, 243));

        btnDeleteSP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDeleteSP.setText("Delete ");
        btnDeleteSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSPActionPerformed(evt);
            }
        });
        jPanel5.add(btnDeleteSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 150, 30));

        btnLuuHoaDon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuuHoaDon.setText("Lưu Hóa Đơn");
        btnLuuHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuHoaDonActionPerformed(evt);
            }
        });
        jPanel5.add(btnLuuHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 130, 30));

        cbxkhachhang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoàng Văn C" }));
        jPanel5.add(cbxkhachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 62, 180, 40));

        btnDanhSachHoaDon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDanhSachHoaDon.setText("Danh Sách Hóa Đơn");
        btnDanhSachHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachHoaDonActionPerformed(evt);
            }
        });
        jPanel5.add(btnDanhSachHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 170, 30));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, DateChooser, org.jdesktop.beansbinding.ELProperty.create("chọn ngày lập hóa đơn( ngày hiện tại)"), DateChooser, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
        bindingGroup.addBinding(binding);

        jPanel5.add(DateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 160, 40));

        lblHInh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblHInh.setOpaque(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lblHInh, org.jdesktop.beansbinding.ELProperty.create("đây là ảnh của khứa nhân viên nè"), lblHInh, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
        bindingGroup.addBinding(binding);

        lblHInh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHInhMouseClicked(evt);
            }
        });
        jPanel5.add(lblHInh, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 220, 180));

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lblUsername, org.jdesktop.beansbinding.ELProperty.create("Username của khứa nhân viên login á"), lblUsername, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
        bindingGroup.addBinding(binding);

        jPanel5.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 170, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnXemTruoc)
                        .addGap(92, 92, 92)
                        .addComponent(btnReset)
                        .addGap(93, 93, 93)
                        .addComponent(btnIn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXemTruoc)
                            .addComponent(btnReset)
                            .addComponent(btnIn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        area.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblGiohangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGiohangMouseClicked
     
        try {
            if (evt.getClickCount() >= 2) {
                MaSP = tblGiohang.getValueAt(tblGiohang.getSelectedRow(), 1).toString();
                System.out.println(MaSP);
                 String TenSP;
                 sp = spdao.selectByKeyword(MaSP +"");
                 TenSP = sp.get(0).getTenSP();
               
                double ThanhTien, DonGia;
                
                DonGia = Double.parseDouble(tblGiohang.getValueAt(tblGiohang.getSelectedRow(), 2).toString());
                SoLuong = Double.parseDouble(tblGiohang.getValueAt(tblGiohang.getSelectedRow(), 3).toString());
                ThanhTien = DonGia * SoLuong;
              
//            ChonSPJDialog chon = new ChonSPJDialog(this, true);
//            chon.setVisible(true);
//            this.dispose();
                this.ThemHoaDonCT(MaSP, TenSP, SoLuong, DonGia, ThanhTien);
                lblTongTien.setText(GioHangDAO.DinhDangTien(TongTien()));
               

                
            }
        } catch (Exception e) {
            
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblGiohangMouseClicked

    private void btnDeleteSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSPActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM HoaDon WHERE MaHD=?";

            this.fillTable();

            MsgBox.alert(this, "xóa thành công");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnDeleteSPActionPerformed

    private void btnChonThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonThemSPActionPerformed
        // TODO add your handling code here:
        QLSanPhamJDialog dialog = new QLSanPhamJDialog(null, true);
        dialog.setVisible(true);
       // this.dispose();
    }//GEN-LAST:event_btnChonThemSPActionPerformed

    private void btnXemTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemTruocActionPerformed

     area.setText(" ******************************************************* \n");
        area.setText(area.getText() + " *                                                                                                * \n");
        area.setText(area.getText() + " *-------------------- SHOWROOM Ô TÔ ETERNAL  -----------------* \n");
        area.setText(area.getText() + " *                                                                                                * \n");
        area.setText(area.getText() + " *                              PHIẾU THANH TOÁN                               * \n");
        area.setText(area.getText() + " *--------------------------------------***--------------------------------------* " + "\n");

        Date obj = new Date();

        String date = obj.toString();
        int i = tblHoaDon.getRowCount();
        area.setText(area.getText() + "\n" + date + "\n\n");
        //area.setText(area.getText() +"\n Ngày Lập Hóa Đơn"+  txtNgayLap.getText() );
        //area.setText(area.getText() + "\n Mã Khách Hàng:  " + txtTenKH.getText() + "\n");
        area.setText(area.getText() + "\n Mã Khách hàng:  " + cbxkhachhang.getSelectedItem()+ "\n");
         area.setText(area.getText() + "\n Mã Nhân Viên:  " + Auth.user.getMaNV()+ "\n");
        area.setText(area.getText() + "\n Ngày lập:  " + DateChooser.getDate()+ "\n");
        if (rdoThanhToanXong.isSelected()) {
            area.setText(area.getText() + "\n Trạng thái: đã thanh toán"+ "\n");
        } else if (rdoTraGop.isSelected()) {
            area.setText(area.getText() + "\n Trạng thái: chưa thanh toán"+ "\n");
        }
       // area.setText(area.getText() + "\n Ghi Chú  " + txtGhiChu.getText() + "\n\n");
      // area.setText(area.getText() +"\n mã qr: " + lblQRCode.getIcon()+ "\n");


        area.setText(area.getText() + "-------------------------------------------------------------------------" + "\n\n");
        area.setText(area.getText() + "-------------------------------------------------------------------------" + "\n\n");
        area.setText(area.getText() + " STT || " + " Mã SP || " + "Tên SP || "+ " Số lượng || " + "  Đơn giá  || " + "  Thành Tiền  || "+ "\n");
        area.setText(area.getText() + "-------------------------------------------------------------------------" + "\n");

        for (int row = 0; row < i; row++) {
            area.setText(area.getText() + "\n " + tblHoaDon.getValueAt(row, 0) + "  ||  ");
            area.setText(area.getText() + tblHoaDon.getValueAt(row, 1) + "   || ");
            area.setText(area.getText() +  tblHoaDon.getValueAt(row, 2) + "   ||  ");
            area.setText(area.getText() +tblHoaDon.getValueAt(row, 3) + "  ||  ");
            area.setText(area.getText() +"$" +  tblHoaDon.getValueAt(row, 4) + "   ||    ");
            area.setText(area.getText() + tblHoaDon.getValueAt(row, 5) + "   ||  "+ "\n");
        }
        area.setText(area.getText() + "-------------------------------------------------------------------------" + "\n");
       

        area.setText(area.getText() + "\n                                      Tiền thực nhận : $ " + txtTienNhan.getText() + "\n\n");
        area.setText(area.getText() + "                                        Tổng tiền :$ " + lblTongTien.getText() + "\n\n");
        area.setText(area.getText() + "                                        Tiền thừa :" + lbl_TienThua.getText() + "\n\n");

        area.setText(area.getText() + "-------------------------------------------------------------------------" + "\n\n");
        area.setText(area.getText() + "\n                          Cảm ơn quý khách hàng đã mua hàng");
    }//GEN-LAST:event_btnXemTruocActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        // TODO add your handling code here:
        try {      
            area.print();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnInActionPerformed

    private void txtTienNhanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienNhanKeyReleased
        // TODO add your handling code here:
        try {
             double tienthua = Double.parseDouble(txtTienNhan.getText()) - GioHangDAO.ChuyenTien(lblTongTien.getText());
        lbl_TienThua.setText(GioHangDAO.DinhDangTien(tienthua) + " $");
        } catch (Exception e) {
           MsgBox.alert(this, "phải nhập số tiền");
        }
       
    }//GEN-LAST:event_txtTienNhanKeyReleased

    private void lbl_TienThuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_TienThuaKeyReleased
        // TODO add your handling code here:
        //        double tienthua = Double.parseDouble(txtTienNhan.getText()) - HoaDonDAO.ChuyenTien(lblTongTien.getText());
        //        lbl_TienThua.setText(HoaDonDAO.DinhDangTien(tienthua)+" VND");
    }//GEN-LAST:event_lbl_TienThuaKeyReleased

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        

    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void btnLuuHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuHoaDonActionPerformed
        // TODO add your handling code here:
           
          
        try {
           QRcode();
            HoaDon hd = new HoaDon();
      //  qlhd.setMaHD(Integer.parseInt(txtMaHD.getText()));
        hd.setNgayLap(DateChooser.getDate());
        hd.setMaGH(Integer.parseInt(txtMaGH.getText()));
        hd.setMaNV(Auth.user.getMaNV());
        hd.setTenKH(cbxkhachhang.getSelectedItem().toString());
        hd.setTongTien(XDate.ChuyenTien(lblTongTien.getText().trim()));
        hd.setQrCode(f.getName());
        hddao.insert(hd);

       MsgBox.alert(this, "Thêm thành công");
       
        } catch (Exception e) {
           MsgBox.alert(this, "Thêm thất bại");
        }
      
    }//GEN-LAST:event_btnLuuHoaDonActionPerformed

    private void rdoTraGopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTraGopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoTraGopActionPerformed

    private void btnDanhSachHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachHoaDonActionPerformed
        // TODO add your handling code here:
        DanhSachHoaDon dialog = new DanhSachHoaDon(this, true);
        dialog.setVisible(true);
        //this.ThemHoaDonCTTheoID(MaHoaDon);
    }//GEN-LAST:event_btnDanhSachHoaDonActionPerformed

    private void lblHInhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHInhMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_lblHInhMouseClicked
 
    
//    private void ThemHDTuTable(int MaHD) {
//        for (int i = 0; i < tblHoaDon.getRowCount(); i++) {
//            int masp = Integer.parseInt(tblHoaDon.getValueAt(i, 1).toString());
//            int soluong = Integer.parseInt(tblHoaDon.getValueAt(i, 3).toString());
//            double thanhtien = XDate.ChuyenTien(tblHoaDon.getValueAt(i, 5).toString());
//            
//           
//            HoaDon qlhd = new HoaDon();
//           // qlhd.setMaHD(MaHD);
//            qlhd.setTongTien(thanhtien);
//           
//            qlhddao.insert(qlhd);
//          
//        }
//    }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GioHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GioHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GioHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GioHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GioHangJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JTextArea area;
    private javax.swing.JButton btnChonThemSP;
    private javax.swing.JButton btnDanhSachHoaDon;
    private javax.swing.JButton btnDeleteSP;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnLuuHoaDon;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnXemTruoc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxkhachhang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblHInh;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lbl_TienThua;
    private javax.swing.JRadioButton rdoThanhToanXong;
    private javax.swing.JRadioButton rdoTraGop;
    private javax.swing.JTable tblGiohang;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtMaGH;
    private javax.swing.JTextField txtTienNhan;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    void init(){ 
        lblUsername.setText(Auth.user.Username);
        File path = new File("src/com/source/ImgNhanVien\\"+Auth.user.hinh).getAbsoluteFile();
 setIconImage(XImages.getAppIcon());
        ImageIcon imagel = new ImageIcon(path.toString());
        lblHInh.setIcon(imagel);
    }
    File f;
    OutputStream out;
     QRCodeWriter QRcode() {
        String tiengviet = "UTF-8";
        String content = "Hóa đơn thanh toán\n"
                + "   Mã Khách Hàng : " + cbxkhachhang.getSelectedItem()+ "\n"
                + "   Mã hóa đơn: " + txtMaGH.getText() + "\n"
                + "   Mã Nhân Viên : " +  Auth.user.getMaNV( )+ "\n"
                + "   Ngày Lập HD : " +  DateChooser.getDate()  + " \n"
                + "   Tổng tiền : "+  lblTongTien.getText()+ " \n"
                + "   Tiền Khách Đưa : " + txtTienNhan.getText() + " \n"
                + "   Tiền Trả :  " + lbl_TienThua.getText() + "\n";
               

        QRCodeWriter qrcodeWriter = new QRCodeWriter();

        try {
            Hashtable hint = new Hashtable();
            hint.put(EncodeHintType.CHARACTER_SET,"UTF-8" );
            BitMatrix bitmatrix = qrcodeWriter.encode(content, BarcodeFormat.QR_CODE, 400, 400,hint);
//            BitMatrix matrix = new MultiFormatWriter().encode(
//            new String(content.getBytes(tiengviet), tiengviet),
//            BarcodeFormat.QR_CODE, 100, 100);
            StringBuilder tenanhQR = new StringBuilder("");
            int random = 0;
            for (int i = 0; i < 10; i++) {
                random = (int) Math.round(Math.random() * 9);
                tenanhQR.append(random);
                System.out.println(random);
            }
            f = new File("src\\com\\source\\qrcodeHoaDon\\" + tenanhQR + ".jpg");
            out = new FileOutputStream(f);
            System.out.println(f); 
            MatrixToImageWriter.writeToStream(bitmatrix, "jpg", out);
       
        } catch (Exception e) {
        }
        return qrcodeWriter;
    }
 
       void chonAnh() {
        JFileChooser fc = new JFileChooser();
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile(); // lưu hình vào thư mục logo
            XImages.save(file);
            ImageIcon icon = XImages.readHinhSP(file.getName()); // đọc hình từ logos
            lblHInh.setIcon(icon);
            System.out.println(icon);
            lblHInh.setToolTipText(file.getName()); // giữ tên hình trong tooltip

        }
       }
}
