/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.source.view;

import com.source.utils.Auth;
import com.source.utils.MsgBox;
import com.source.utils.XImages;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author DELL
 */
public class RUN_MAIN extends javax.swing.JFrame {

    /**
     * Creates new form ManHinhChonJFrame
     */
    public RUN_MAIN() {
        initComponents();
        this.setLocationRelativeTo(null);
        new A_ChaoJDialog(this, true).setVisible(true);
        new A_DangNhapJDialog(this, true).setVisible(true);
        
        init();
    }
        public RUN_MAIN(int x) {
        initComponents();
        this.setLocationRelativeTo(null);
//        new A_ChaoJDialog(this, true).setVisible(true);
//        new A_DangNhapJDialog(this, true).setVisible(true);
        
        init();
    }
    public void init(){
        this.setLocationRelativeTo(null);
        startdongHo();
         setIconImage(XImages.getAppIcon());
        ChuChay();
    }
    
     javax.swing.Timer t ;
    public void ChuChay() {
        ActionListener a;
            a = new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                            String lbl = lblchay.getText();
                                lbl = lbl.substring(1, lbl.length())+lbl.charAt(0);
                                lblchay.setText(lbl);
                }
            };
       
          t = new javax.swing.Timer(200, a);
          t.start();
        
    }
    void startdongHo() {
        new Timer(1000, new ActionListener() {
            SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a");

            @Override
            public void actionPerformed(ActionEvent e) { 
                lbldongho.setText(format.format(new Date()));
            }
        }).start();
    }
    
    public void setColor(JPanel panel){
        panel.setBackground(new java.awt.Color(150,150,150));
    }
     public void resetColor(JPanel panel){
        panel.setBackground(new java.awt.Color(255,255,255));
    }
      public void resetColor51(JPanel panel){
        panel.setBackground(new java.awt.Color(0,0,0));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        pnlbanhang = new javax.swing.JPanel();
        lbliconbanhang = new javax.swing.JLabel();
        lblbanhang = new javax.swing.JLabel();
        pnlquanly = new javax.swing.JPanel();
        lbliconquanly = new javax.swing.JLabel();
        lblquanly = new javax.swing.JLabel();
        pnl2 = new javax.swing.JPanel();
        lbleternal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnl10 = new javax.swing.JPanel();
        lbldangxuat2 = new javax.swing.JLabel();
        pnl11 = new javax.swing.JPanel();
        lblcaidat1 = new javax.swing.JLabel();
        lbldongho = new javax.swing.JLabel();
        pnl9 = new javax.swing.JPanel();
        lblweb1 = new javax.swing.JLabel();
        pnl12 = new javax.swing.JPanel();
        lblcolor1 = new javax.swing.JLabel();
        lblchay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnl1.setBackground(new java.awt.Color(255, 255, 255));
        pnl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        pnlbanhang.setBackground(new java.awt.Color(255, 255, 255));
        pnlbanhang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        pnlbanhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlbanhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlbanhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlbanhangMouseExited(evt);
            }
        });

        lbliconbanhang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbliconbanhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Icon/ShoppTrang.png"))); // NOI18N
        lbliconbanhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbliconbanhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbliconbanhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbliconbanhangMouseExited(evt);
            }
        });

        lblbanhang.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblbanhang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbanhang.setText("BÁN HÀNG");
        lblbanhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbanhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblbanhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblbanhangMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlbanhangLayout = new javax.swing.GroupLayout(pnlbanhang);
        pnlbanhang.setLayout(pnlbanhangLayout);
        pnlbanhangLayout.setHorizontalGroup(
            pnlbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlbanhangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblbanhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lbliconbanhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlbanhangLayout.setVerticalGroup(
            pnlbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlbanhangLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbliconbanhang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblbanhang)
                .addContainerGap())
        );

        pnlquanly.setBackground(new java.awt.Color(255, 255, 255));
        pnlquanly.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        pnlquanly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlquanlyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlquanlyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlquanlyMouseExited(evt);
            }
        });

        lbliconquanly.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbliconquanly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Icon/StossDen.png"))); // NOI18N
        lbliconquanly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbliconquanlyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbliconquanlyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbliconquanlyMouseExited(evt);
            }
        });

        lblquanly.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblquanly.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblquanly.setText("QUẢN LÝ");
        lblquanly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblquanlyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblquanlyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblquanlyMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlquanlyLayout = new javax.swing.GroupLayout(pnlquanly);
        pnlquanly.setLayout(pnlquanlyLayout);
        pnlquanlyLayout.setHorizontalGroup(
            pnlquanlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquanlyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblquanly, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lbliconquanly, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlquanlyLayout.setVerticalGroup(
            pnlquanlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquanlyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbliconquanly)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblquanly)
                .addGap(12, 12, 12))
        );

        pnl2.setBackground(new java.awt.Color(255, 255, 255));
        pnl2.setLayout(new java.awt.BorderLayout());

        lbleternal.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        lbleternal.setForeground(new java.awt.Color(51, 51, 51));
        lbleternal.setText("ETERNAL");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        pnl10.setBackground(new java.awt.Color(0, 0, 0));
        pnl10.setLayout(new java.awt.BorderLayout());

        lbldangxuat2.setBackground(new java.awt.Color(255, 255, 255));
        lbldangxuat2.setForeground(new java.awt.Color(255, 255, 255));
        lbldangxuat2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldangxuat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Icon/offWhite.png"))); // NOI18N
        lbldangxuat2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldangxuat2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbldangxuat2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbldangxuat2MouseExited(evt);
            }
        });
        pnl10.add(lbldangxuat2, java.awt.BorderLayout.CENTER);

        pnl11.setBackground(new java.awt.Color(0, 0, 0));
        pnl11.setLayout(new java.awt.BorderLayout());

        lblcaidat1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcaidat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Icon/SettingsWhite.png"))); // NOI18N
        lblcaidat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcaidat1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcaidat1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcaidat1MouseExited(evt);
            }
        });
        pnl11.add(lblcaidat1, java.awt.BorderLayout.CENTER);

        lbldongho.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbldongho.setForeground(new java.awt.Color(255, 255, 255));
        lbldongho.setText("00:00:00 PM");

        pnl9.setBackground(new java.awt.Color(0, 0, 0));
        pnl9.setLayout(new java.awt.BorderLayout());

        lblweb1.setForeground(new java.awt.Color(255, 255, 255));
        lblweb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblweb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Icon/WedWhite.png"))); // NOI18N
        lblweb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblweb1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblweb1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblweb1MouseExited(evt);
            }
        });
        pnl9.add(lblweb1, java.awt.BorderLayout.CENTER);

        pnl12.setBackground(new java.awt.Color(0, 0, 0));
        pnl12.setLayout(new java.awt.BorderLayout());

        lblcolor1.setBackground(new java.awt.Color(0, 0, 0));
        lblcolor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcolor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/source/Icon/colorWhite.png"))); // NOI18N
        lblcolor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcolor1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcolor1MouseExited(evt);
            }
        });
        pnl12.add(lblcolor1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnl10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(lbldongho)
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbldongho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnl10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pnl12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblchay.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblchay.setForeground(new java.awt.Color(0, 153, 153));
        lblchay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblchay.setText("     CHÀO MỪNG ĐẾN VỚI SHOWROOM ETERNAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblchay, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblchay)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbleternal)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addComponent(pnlbanhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(pnlquanly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
            .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbleternal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlbanhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlquanly, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                    .addGap(0, 332, Short.MAX_VALUE)
                    .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(pnl1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbliconbanhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbliconbanhangMouseClicked
        // TODO add your handling code here:
        new QLSanPhamJDialog(this, true).setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_lbliconbanhangMouseClicked

    private void lbliconquanlyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbliconquanlyMouseClicked
        // TODO add your handling code here:
//        this.dispose();
        new C_QuanLyALLJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lbliconquanlyMouseClicked

    private void pnlquanlyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlquanlyMouseClicked
        // TODO add your handling code here:
//        this.dispose();
        new C_QuanLyALLJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_pnlquanlyMouseClicked

    private void lblquanlyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblquanlyMouseClicked
        // TODO add your handling code here:
//        this.dispose();
        new C_QuanLyALLJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblquanlyMouseClicked

    private void lbliconbanhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbliconbanhangMouseEntered
        // TODO add your handling code here:
        setColor(pnlbanhang);
    }//GEN-LAST:event_lbliconbanhangMouseEntered

    private void pnlbanhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlbanhangMouseExited
        // TODO add your handling code here:
        resetColor(pnlbanhang);
    }//GEN-LAST:event_pnlbanhangMouseExited

    private void pnlbanhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlbanhangMouseEntered
        // TODO add your handling code here:
        setColor(pnlbanhang);
    }//GEN-LAST:event_pnlbanhangMouseEntered

    private void pnlbanhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlbanhangMouseClicked
        // TODO add your handling code here:
        new QLSanPhamJDialog(this, true).setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_pnlbanhangMouseClicked

    private void lblbanhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbanhangMouseClicked
        // TODO add your handling code here:
        new QLSanPhamJDialog(this, true).setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_lblbanhangMouseClicked

    private void lbliconbanhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbliconbanhangMouseExited
        // TODO add your handling code here:
        resetColor(pnlbanhang);
    }//GEN-LAST:event_lbliconbanhangMouseExited

    private void lblbanhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbanhangMouseExited
        // TODO add your handling code here:
        resetColor(pnlbanhang);
    }//GEN-LAST:event_lblbanhangMouseExited

    private void lblbanhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbanhangMouseEntered
        // TODO add your handling code here:
        setColor(pnlbanhang);
    }//GEN-LAST:event_lblbanhangMouseEntered

    private void lbliconquanlyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbliconquanlyMouseExited
        // TODO add your handling code here:
        resetColor(pnlquanly);
    }//GEN-LAST:event_lbliconquanlyMouseExited

    private void lbliconquanlyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbliconquanlyMouseEntered
        // TODO add your handling code here:
        setColor(pnlquanly);
    }//GEN-LAST:event_lbliconquanlyMouseEntered

    private void lblquanlyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblquanlyMouseExited
        // TODO add your handling code here:
        resetColor(pnlquanly);
    }//GEN-LAST:event_lblquanlyMouseExited

    private void lblquanlyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblquanlyMouseEntered
        // TODO add your handling code here:
        setColor(pnlquanly);
    }//GEN-LAST:event_lblquanlyMouseEntered

    private void pnlquanlyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlquanlyMouseExited
        // TODO add your handling code here:
        resetColor(pnlquanly);
    }//GEN-LAST:event_pnlquanlyMouseExited

    private void pnlquanlyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlquanlyMouseEntered
        // TODO add your handling code here:
        setColor(pnlquanly);
    }//GEN-LAST:event_pnlquanlyMouseEntered

    private void lbldangxuat2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangxuat2MouseClicked
        // TODO add your handling code here:
        new A_DangXuatJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lbldangxuat2MouseClicked

    private void lbldangxuat2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangxuat2MouseEntered
        // TODO add your handling code here:
        setColor(pnl10);
    }//GEN-LAST:event_lbldangxuat2MouseEntered

    private void lbldangxuat2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangxuat2MouseExited
        // TODO add your handling code here:
        resetColor51(pnl10);
    }//GEN-LAST:event_lbldangxuat2MouseExited

    private void lblcaidat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcaidat1MouseClicked
        // TODO add your handling code here:
        new BCaiDatJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblcaidat1MouseClicked

    private void lblcaidat1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcaidat1MouseEntered
        // TODO add your handling code here:
        setColor(pnl11);
    }//GEN-LAST:event_lblcaidat1MouseEntered

    private void lblcaidat1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcaidat1MouseExited
        // TODO add your handling code here:
        resetColor51(pnl11);
    }//GEN-LAST:event_lblcaidat1MouseExited

    private void lblweb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblweb1MouseClicked
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new File("help/index.html").toURI());
        } catch (IOException ex) {
            MsgBox.alert(this, "Không tìm thấy file hướng dẫn!");
            System.out.println(ex);
        }
    }//GEN-LAST:event_lblweb1MouseClicked

    private void lblweb1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblweb1MouseEntered
        // TODO add your handling code here:
        setColor(pnl9);
    }//GEN-LAST:event_lblweb1MouseEntered

    private void lblweb1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblweb1MouseExited
        // TODO add your handling code here:
        resetColor51(pnl9);
    }//GEN-LAST:event_lblweb1MouseExited

    private void lblcolor1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcolor1MouseEntered
        // TODO add your handling code here:
        setColor(pnl12);
    }//GEN-LAST:event_lblcolor1MouseEntered

    private void lblcolor1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcolor1MouseExited
        // TODO add your handling code here:
        resetColor51(pnl12);
    }//GEN-LAST:event_lblcolor1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RUN_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RUN_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RUN_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RUN_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RUN_MAIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblbanhang;
    private javax.swing.JLabel lblcaidat1;
    private javax.swing.JLabel lblchay;
    private javax.swing.JLabel lblcolor1;
    private javax.swing.JLabel lbldangxuat2;
    private javax.swing.JLabel lbldongho;
    private javax.swing.JLabel lbleternal;
    private javax.swing.JLabel lbliconbanhang;
    private javax.swing.JLabel lbliconquanly;
    private javax.swing.JLabel lblquanly;
    private javax.swing.JLabel lblweb1;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl10;
    private javax.swing.JPanel pnl11;
    private javax.swing.JPanel pnl12;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl9;
    private javax.swing.JPanel pnlbanhang;
    private javax.swing.JPanel pnlquanly;
    // End of variables declaration//GEN-END:variables
}
